In [3]:
import glob
import pandas as pd

# get data file names
path =r'/Users/nish/Downloads/Company Files/test'
filenames = glob.glob(path + "/*.csv")

dic = {}
flag = True

def retDataFrame(filename):   
    tDf1 = pd.read_csv(filename)
    tDf2 = tDf1.groupby('COMPANY_STATUS').size()
    tDf3 = tDf2.to_frame(name=None).T
    tDf4 = tDf3.rename(index={0: b[0]})
    return tDf4;

for filename in filenames:
    a=filename.split('_')
    b=a[6].split('.')
    if flag:
        mn_tble = retDataFrame(filename)
        flag = False
        continue
    dic[b[0]] = retDataFrame(filename)

# Concatenate all data into one DataFrame
mn_tble = pd.concat(dic.values())
mn_tble

,ACTIVE,ACTIVE IN PROGRESS,AMALGAMATED,CONVERTED TO LLP,CONVERTED TO LLP AND DISSOLVED,DEFAULT,DISSOLVED,DORMANT,"Dormant under section 455 of Companies Act, 2013",LIQUIDATED,STRIKE OFF,UNDER LIQUIDATION,UNDER PROCESS OF STRIKING OFF
Dadra Nagar Haveli,341,NaN,6.0,NaN,1.0,NaN,NaN,38.0,NaN,NaN,35.0,NaN,10.0
Haryana,21185,3.0,124.0,4.0,9.0,NaN,2.0,2167.0,24.0,1.0,2427.0,29.0,139.0
Punjab,15346,3.0,121.0,3.0,15.0,NaN,1.0,2013.0,4.0,NaN,8405.0,113.0,142.0
Goa,4853,NaN,157.0,3.0,18.0,NaN,5.0,443.0,NaN,4.0,1227.0,11.0,632.0
Chhattisgarh,6212,1.0,13.0,4.0,16.0,NaN,NaN,244.0,1.0,NaN,1017.0,1.0,15.0
Kerala,24835,6.0,98.0,2.0,4.0,NaN,1434.0,2212.0,25.0,NaN,8774.0,296.0,219.0
Bihar,12653,6.0,4.0,2.0,2.0,NaN,14.0,1208.0,5.0,1.0,2410.0,41.0,3323.0
Tamil Nadu,69082,25.0,1057.0,35.0,103.0,NaN,805.0,15405.0,12.0,386.0,25382.0,283.0,1853.0
Chandigarh,7445,NaN,35.0,1.0,17.0,1.0,NaN,1103.0,NaN,NaN,3932.0,68.0,63.0
Jammu,2318,1.0,13.0,NaN,NaN,NaN,3.0,978.0,NaN,2.0,593.0,15.0,69.0
Jharkhand,6430,1.0,8.0,1.0,4.0,NaN,10.0,614.0,NaN,3.0,1067.0,12.0,770.0
Meghalaya,533,NaN,4.0,NaN,NaN,NaN,NaN,13.0,NaN,NaN,316.0,1.0,69.0
Delhi,197051,27.0,3078.0,189.0,532.0,NaN,109.0,28168.0,65.0,54.0,40966.0,689.0,1441.0
Assam,5106,NaN,65.0,5.0,5.0,NaN,4.0,174.0,NaN,1.0,2644.0,14.0,1245.0
Madhya Pradesh,20753,2.0,65.0,10.0,28.0,NaN,NaN,1335.0,2.0,2.0,7298.0,65.0,222.0
Lakshadweep,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Manipur,189,1.0,NaN,NaN,NaN,NaN,NaN,17.0,NaN,NaN,153.0,NaN,36.0
Uttar Pradesh,48079,5.0,197.0,24.0,66.0,NaN,5.0,4327.0,7.0,16.0,11107.0,214.0,1118.0
West Bengal,137172,3.0,3952.0,228.0,457.0,NaN,613.0,790.0,21.0,26.0,38685.0,653.0,2452.0
Uttarakhand,3553,NaN,3.0,NaN,2.0,NaN,NaN,82.0,NaN,3.0,743.0,14.0,265.0
Andhra Pradesh,13397,7.0,72.0,4.0,8.0,NaN,NaN,5390.0,NaN,1.0,2061.0,53.0,212.0
Puducherry,1353,1.0,23.0,NaN,NaN,NaN,8.0,228.0,NaN,NaN,1117.0,8.0,8.0
Nagaland,151,NaN,1.0,NaN,NaN,NaN,NaN,25.0,NaN,NaN,261.0,1.0,37.0
Gujarat,52550,8.0,1063.0,78.0,212.0,NaN,49.0,10843.0,7.0,NaN,12939.0,570.0,2865.0
Arunachal Pradesh,183,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,234.0,2.0,61.0
Maharashtra,215447,71.0,4023.0,317.0,1206.0,NaN,5765.0,33907.0,24.0,517.0,29858.0,1272.0,2300.0
Tripura,207,NaN,1.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,80.0,NaN,40.0
Telangana,51743,21.0,402.0,31.0,24.0,NaN,1.0,17210.0,1.0,18.0,6448.0,223.0,918.0
Daman Diu,191,NaN,6.0,NaN,1.0,NaN,NaN,14.0,1.0,1.0,49.0,2.0,33.0
Karnataka,53761,7.0,590.0,24.0,66.0,NaN,240.0,7877.0,8.0,1.0,14587.0,496.0,867.0
Mizoram,29,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,53.0,NaN,7.0
Odisha,11989,1.0,56.0,3.0,NaN,NaN,57.0,566.0,3.0,1.0,5433.0,64.0,228.0
Himachal,3049,NaN,28.0,NaN,2.0,NaN,NaN,412.0,1.0,NaN,1081.0,20.0,130.0

#get data file names
path =r'/Users/nish/Downloads/Company Files/test'
filenames = glob.glob(path + "/*.csv")

dic = {}
flag = True

def retDataFrame(filename):   
    tDf1 = pd.read_csv(filename)
    tDf2 = tDf1.groupby('COMPANY_STATUS').size()
    tDf3 = tDf2.to_frame(name=None).T
    tDf4 = tDf3.rename(index={0: b[0]})
    return tDf4;

for filename in filenames:
    a=filename.split('_')
    b=a[6].split('.')
    if flag:
        mn_tble = retDataFrame(filename)
        flag = False
        continue
    dic[b[0]] = retDataFrame(filename)

#Concatenate all data into one DataFrame
mn_tble = pd.concat(dic.values())
mn_tble

In [13]:
path =r'/Users/nish/Downloads/Company Files/test'
filenames = glob.glob(path + "/*.csv")

dic = {}
flag = True

def retDataFrame(filename):   
    tDf1 = pd.read_csv(filename)
    tDf2 = tDf1.groupby('COMPANY_STATUS').size()
    tDf3 = tDf2.to_frame(name=None).T
    tDf4 = tDf3.rename(index={0: b[0]})
    return tDf4;

In [9]:
tDf4

NameError: name 'tDf4' is not defined

In [12]:
b

['West Bengal', 'csv']

In [ ]:
a